/**
 * 2027 HKDSE 已確認筆試時間（單一資料來源）
 * -----------------------------------------
 * 日期以香港時間 Asia/Hong_Kong 計算。
 * 上午場次預設 08:30；如考評局公布不同開考時間，只改 startTime。
 *
 * 故意省略（時間表註 2，日期尚未落實）：
 * - 英語文學、科技與生活、體育、音樂
 * - 4 月 7 日只列中國文學（略過科技與生活）
 * - 4 月 20 日只列設計與應用科技（略過英語文學）
 * - 4 月 29 日、5 月 3 日整日不列出（全屬未落實科目）
 * - 實習／口試時段、後備日
 */
(function (global) {
  global.DSE2027_CONFIG = {
    timezone: "Asia/Hong_Kong",
    defaultStartTime: "08:30:00",
    year: 2027,
    sourceLabel: "HKEAA 2027 考試時間表",
    subjects: [
      {
        id: "visual-arts",
        name: "視覺藝術",
        subtitle: "卷一及卷二",
        date: "2027-04-06",
        weekday: "星期二",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "chi-lit",
        name: "中國文學",
        subtitle: "卷一及卷二",
        date: "2027-04-07",
        weekday: "星期三",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "chi-lang",
        name: "中國語文",
        subtitle: "卷一及卷二",
        date: "2027-04-08",
        weekday: "星期四",
        startTime: "08:30:00",
        hero: true,
      },
      {
        id: "eng-12",
        name: "英國語文（一）及（二）",
        subtitle: "閱讀及寫作",
        date: "2027-04-09",
        weekday: "星期五",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "eng-3",
        name: "英國語文（三）（聆聽及綜合能力）",
        subtitle: "聆聽及綜合能力考核",
        date: "2027-04-10",
        weekday: "星期六",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "math-cp",
        name: "數學必修部分",
        subtitle: "卷一及卷二",
        date: "2027-04-12",
        weekday: "星期一",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "csd",
        name: "公民與社會發展",
        subtitle: "筆試",
        date: "2027-04-13",
        weekday: "星期二",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "hmsc",
        name: "健康管理與社會關懷",
        subtitle: "卷一及卷二",
        date: "2027-04-14",
        weekday: "星期三",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "chem",
        name: "化學",
        subtitle: "卷一及卷二",
        date: "2027-04-15",
        weekday: "星期四",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "geog",
        name: "地理",
        subtitle: "卷一及卷二",
        date: "2027-04-16",
        weekday: "星期五",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "ict",
        name: "資訊及通訊科技",
        subtitle: "卷一及卷二",
        date: "2027-04-17",
        weekday: "星期六",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "bio",
        name: "生物",
        subtitle: "卷一及卷二",
        date: "2027-04-19",
        weekday: "星期一",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "dat",
        name: "設計與應用科技",
        subtitle: "卷一及卷二",
        date: "2027-04-20",
        weekday: "星期二",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "phy",
        name: "物理",
        subtitle: "卷一及卷二",
        date: "2027-04-21",
        weekday: "星期三",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "econ",
        name: "經濟",
        subtitle: "卷一及卷二",
        date: "2027-04-22",
        weekday: "星期四",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "math-m",
        name: "數學延伸部分（單元一及二）",
        subtitle: "單元一及單元二",
        date: "2027-04-23",
        weekday: "星期五",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "chi-hist",
        name: "中國歷史",
        subtitle: "卷一及卷二",
        date: "2027-04-24",
        weekday: "星期六",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "bafs",
        name: "企業、會計與財務概論",
        subtitle: "卷一及卷二",
        date: "2027-04-26",
        weekday: "星期一",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "hist",
        name: "歷史",
        subtitle: "卷一及卷二",
        date: "2027-04-27",
        weekday: "星期二",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "ths",
        name: "旅遊與款待",
        subtitle: "卷一及卷二",
        date: "2027-04-28",
        weekday: "星期三",
        startTime: "08:30:00",
        hero: false,
      },
      {
        id: "ers",
        name: "倫理與宗教",
        subtitle: "卷一及卷二",
        date: "2027-04-30",
        weekday: "星期五",
        startTime: "08:30:00",
        hero: false,
      },
    ],
  };
})(typeof window !== "undefined" ? window : globalThis);
